--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/dropmebeat/BetterRTPBedrock-PocketMine
build-by-default: true
branches:
- main
projects:
  BetterRTPBedrock-PocketMine:
    path: ""
...
